FROM apache/airflow:3.1.8

# Copy uv binary from official uv image, avoid installer
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV PATH="/root/.local/bin:$PATH"

# Copy dependency files for caching
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN uv sync --frozen --no-cache