version: 2

models:
   - name: rpt_user_stats
     description: "Users stats report"
     columns:
       - name: user_name
         description: "User name"
         tests:
           - unique
           - not_null
       - name: tot_bookings
         description: "Total number of bookings placed"
         tests:
           - not_null
       - name: tot_amount
         description: "Total amount spent"
         tests:
            - not_null