version: 2

models:
   - name: stg_users
     description: "Postgres users data from backend"
     columns:
       - name: user_id
         description: "Unique user identifier as text"
         tests:
           - unique
           - not_null
       - name: user_name
         description: "Name of the user"
       - name: created_ts
         description: "User creation timestamp"
       - name: sync_ts
         description: "User data airbyte sync timestamp"
         
   - name: stg_bookings
     description: "Postgres bookings data from backend"
     columns:
       - name: booking_id
         description: "Unique booking identifier as bigint"
         tests:
           - unique
           - not_null
       - name: booking_dt
         description: "Date of the booking"
       - name: sync_ts
         description: "User data airbyte sync timestamp"